### PR TITLE
Update spelling 0.0.19

### PR DESCRIPTION
**Pull request by jsoref**
This updates check-spelling for https://github.com/check-spelling/check-spelling/security/advisories/GHSA-g86g-chm8-7r2p

Note that you need to upgrade all branches (the easiest thing to do is to rebase test1 onto `main` after merging this).

### CODE REVIEW

**Review by scout249 — APPROVED** [review]

**Comment by jsoref** [comment]
@scout249: I presume you'll integrate these changes? If not, you really should disable the workflow.

**Comment by scout249** [comment]
@jsoref Thanks for your kindness and assistance. Your pull request has been merged with main.

I currently disabled spell check workflow, It generate a lot of spelling mistake. I have to add our vocab list to the dictionary and there are different dictionary txt file, not sure which one to use.

**Comment by jsoref** [comment]
GitHub doesn't think you've merged it. This PR is listed as closed, not merged and the contents of the workflow on main show the old version.

With this PR, your repository should have been passing. You generally aren't going to want to use the `dictionary.txt` file, the default should be fine for you. To supplement the dictionary, you can add items to `allow.txt`. And generally the bot should suggest changes for `expect.txt`.

**Comment by scout249** [comment]
It is now merged. 👍 

Commit ID: `f9b5894`
https://github.com/scout249/hugo-static-app/commits/main

**Pull request merged**
